MyBlog/MyBlog/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBlog.Controllers
{
    public class ProfileController : Controller
    {
        //
        // GET: /Profile/

        public ActionResult Index()
        {
            return View();
        }

    }
}

MyBlog/MyBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/Main")
    @* or you could put this: < *@
</head>
<body>
    <header>
        <h1>My Blog</h1>
        @if (Request.IsAuthenticated)
        {
            <div>
                Welcome @User.Identity.Name
                &nbsp;|&nbsp;<a href="@Url.Action("Index","Home")">Home</a>
                &nbsp;|&nbsp;<a href="@Url.Action("Index","Profile")">Profile</a>
                &nbsp;|&nbsp;<a href="@Url.Action("Create", "Post")">Create a new post</a>
                &nbsp;|&nbsp;<a href="@Url.Action("Logout", "Account")">Logout</a>
            </div>
        }else{
            <div>
                &nbsp;|&nbsp;<a href="@Url.Action("Index","Home")">Home</a>
                &nbsp;|&nbsp;<a href="@Url.Action("Login", "Account")">Log In</a>
                &nbsp;|&nbsp;<a href="@Url.Action("Register", "Account")">Create A New Account</a>
            </div>
        }
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>